name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x # Replace with your desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: ./publish
          branch: gh-pages
